# Generated by Django 4.2.1 on 2023-05-10 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desert', models.CharField(max_length=100)),
                ('calories', models.CharField(max_length=100)),
                ('fat', models.CharField(max_length=100)),
                ('carbs', models.CharField(max_length=100)),
                ('protein', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Nutrition',
            },
        ),
        migrations.CreateModel(
            name='UserNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dummy_list.nutrition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserNutrition',
            },
        ),
    ]
