# Generated by Django 4.2.1 on 2023-05-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrition',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_nutritions', to='dummy_list.nutrition'),
        ),
    ]
